num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
print("addition:", num1 + num2)
print("subtraction:", num1 - num2)
print("multiplication:", num1 * num2)
print("division:", num1 / num2 if num2 != 0 else "Cannot divide by zero")
